name: pyorerun
channels:
- conda-forge
- default
- opensim-org
dependencies:
- ezc3d
- trc-data-reader>=0.4.0
- rerun-sdk=0.27.2
- numpy
- matplotlib
- biorbd>=1.10.5
- trimesh
- tk
- imageio
- imageio-ffmpeg
- opensim
- pinocchio
- pycollada
# from pip
# pip install trc-data-reader

